### ISSUE TITLE
doi-editor release ui inoperable under Firefox

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/doi-ui#167]
## 🐛 Describe the bug
When attempting to release one of the DOIs listed at https://pds-gamma.jpl.nasa.gov/tools/doi-editor/#/release/urn:nasa:pds:insight_cameras::1.0, the resulting page of the app shows an "API Unreachable" error banner and is inoperable.

This is specific to Firefox - the webapp works correctly under safari and chrome

## 📜 To Reproduce
1. Navigate to https://pds-gamma.jpl.nasa.gov/tools/doi-editor/#/release/urn:nasa:pds:insight_cameras::1.0
2. Click on "RELEASE" for one of the DOIs

## 🕵️ Expected behavior
@jordanpadams is Firefox intended to be supported?  If so, the app should be made compatible.  If not, I'd suggest detection of FF clients, and a corresponding warning be shown instead of the current page with error.

## 📚 Version of Software Used
pds-dio-ui==1.0.1
firefox==106.0.3 (64-bit)

**Comment by jordanpadams** [comment]
@eddiesarevalo @anilnatha do we know of a tool we can use in order to effectively test all browsers for web apps? some folks at RMS mentioned a tool a while back for this, but not sure if you know of others or could ask around in your group.

@c-suh should probably be looped in here too.

**Comment by alexdunnjpl** [comment]
@jordanpadams [Selenium](https://www.selenium.dev/documentation/webdriver/browsers/)?

There's a learning curve for the full feature set, but the tool's really tight and shouldn't be onerous to ramp up on if we're wanting to get basic tests going.

**Comment by eddiesarevalo** [comment]
The bug that caused a crash on Firefox is fixable by adding the version number to the XSL stylesheet. Firefox is more strict about this than Chrome or Safari. 

https://github.com/NASA-PDS/doi-ui/blob/main/src/utils/xmlUtil.js

It turns out even by fixing this, the `<xsl:output indent="yes"/>'` tag doesn't work on Firefox so that the styling will look jumbled on Firefox.

On Firefox:
![Screen Shot 2022-12-05 at 3.47.43 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/d2fc7539-27ce-457c-8eac-42b71cbc6bd3)

On Chrome:![Screen Shot 2022-12-05 at 3.47.29 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/0d441a62-7485-454e-b061-3903ce2b94ae)

If we want to support firefox we should get rid of the XSL logic and use something off of npm like https://github.com/riversun/xml-beautify

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo can test the new styler, if that does not work will keep it as is with the bug fix on the xml.

**Comment by eddiesarevalo** [comment]
Used a different formatter so it looks formatted in Firefox and Chrome:
<img width="619" alt="Screen Shot 2022-12-20 at 8 53 35 AM" src="https://user-images.githubusercontent.com/5596893/208750885-e7dd6657-9920-40e8-8b83-aee3d0c3d429.png">

**Comment by tloubrieu-jpl** [comment]
cannot be tested because of https://github.com/NASA-PDS/doi-ui/issues/178
