### ISSUE TITLE
Pre-existing keyword show in a weird way in the UI

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#88]
## 🐛 Describe the bug

See for example doi 10.17189/22185 on pds-dev3

![image](https://user-images.githubusercontent.com/60993872/136120773-6bc73a2c-6305-471d-8ef3-7f51e9566fa1.png)

## 📜 To Reproduce

1. search for doi 10.17189/22185
2. click update
3. click published: yes
4. edit keywords

## 🕵️ Expected behavior

The keywords should be in different subject tags

## 🖥 System Info

---

**Comment by eddiesarevalo** [comment]
Looks like that subject (keyword) line was either entered that way or generated on the backend. 
Each subject should be only one keyword but that specific subject (keyword) is the string `['VOYAGER 1','JUPITER','ENERGETIC PARTICLE DETECTOR','VG1','PLANET','LECP','LOW ENERGY CHARGED PARTICLE']`

I was working on parsing it out to show as separate keywords on the UI but then I realized it won't fix it on the backend. At this point there is nothing to prevent a user from entering whatever text they want as a subject (keyword) for example `?#&$#$)(*(akjskldfj`. This should probably be rejected by the server.

According to @tloubrieu-jpl these should no longer occur and there is a user guide that lets a user know how to enter keywords.

I coudn't find any DOIs that still have a subject(keyword) like this. I have been testing by creating them to look like this particular way as doi 10.17189/22185 on pds-dev3 no longer exists.

@collinss-jpl Do you see any more that look like this? Otherwise we should close this as 'will not fix'

**Comment by collinss-jpl** [comment]
@eddiesarevalo I don't think we have any more existing entries like this where the keywords/subjects have been serialized out incorrectly. For this particular entry (`10.17189/22185`), I'm guessing it has already been deleted at some point since I cannot find it on DataCite either. You are correct though that for future cases, it should be corrected on backend first and foremost.

**Comment by tloubrieu-jpl** [comment]
We will close that since it sounds like we don't see this issue anymore.
